### ISSUE TITLE
blocks events

### ISSUE THREAD

**Issue by namecallfilter** [doctor8296/istrusted-bypass#2]
blocks any event i call on it

**Comment by doctor8296** [comment]
Can you send the code and descrabie what are you trying to do?

**Comment by namecallfilter** [comment]
@doctor8296 here:

```ts
import { FindAnswer } from "./modules/GetAnswers";
import { GetElement } from "./modules/Utils/GetElement";
import { Sleep } from "./modules/Utils/Sleep";

const question = GetElement("//span[@class='notranslate lang-en']")?.textContent as string;
FindAnswer(question).then(async (result) => {
	if (result?.answer == null) throw new Error("Answer not found");
	if (result?.type == "text") {
		const input = GetElement("//input") as HTMLInputElement;
		input.setAttribute("value", result?.answer);
		input.dispatchEvent(new Event("input", { bubbles: true }));

		const submitDiv = GetElement("//div[text()='Submit']") as HTMLDivElement;
		submitDiv.dispatchEvent(new Event("click", { bubbles: true, cancelable: true }));

		await Sleep(1000);

		const continueDiv = GetElement("//div[text()='Submit']") as HTMLDivElement;
		continueDiv.dispatchEvent(new Event("click", { bubbles: true, cancelable: true }));
		// document.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter" }));
	}
});

```

**Comment by namecallfilter** [comment]
Even when i click the sumbit button it just doesn't work, the website that I'm trying to use this on it gimkit btw

**Comment by doctor8296** [comment]
@kaorlol are you sure that this method is suitable there? I don't think there is actual isTrusted check. Probably you are triggering wrong event or you should trigger something else.

**Comment by namecallfilter** [comment]
@doctor8296 They do have a check:
![image](https://github.com/69Type/istrusted-bypass/assets/96850544/109dc85e-88dd-4c83-b6cb-4bb3d20b5800)

**Comment by namecallfilter** [comment]
The code i sent above is a little different because it is for text answers but the continue div has the same check

**Comment by doctor8296** [comment]
@kaorlol interesting, I need to see this specific case. Is it possbile to check it on the site, I mean can you provide me the adress and what you trying to do?

**Comment by namecallfilter** [comment]
> @kaorlol interesting, I need to see this specific case. Is it possbile to check it on the site, I mean can you provide me the adress and what you trying to do?

nevermind you were right but I found a diff problem

**Comment by namecallfilter** [comment]
when i do it on a multichoice question I get this error: 
Uncaught TypeError: thisArg[s] is undefined
    apply debugger eval code:19
    <anonymous> debugger eval code:1
debugger eval code:19:27
    apply debugger eval code:19
    <anonymous> debugger eval code:1
    
    code: document.querySelectorAll(".sc-kgDmvS.lsjoO")[1].dispatchEvent(new Event("click", { bubbles: true, cancelable: true }));

**Comment by doctor8296** [comment]
@kaorlol this error means that the addeventlistener method was never called for this element.

**Comment by namecallfilter** [comment]
> @kaorlol this error means that the addeventlistener method was never called for this element.

thats weird because it is in the code

**Comment by doctor8296** [comment]
> > @kaorlol this error means that the addeventlistener method was never called for this element.
> 
> thats weird because it is in the code

Check out the event listeners for element which you are trying to use dispatch on

**Comment by namecallfilter** [comment]
> > > @kaorlol this error means that the addeventlistener method was never called for this element.
> > 
> > 
> > thats weird because it is in the code
> 
> Check out the event listeners for element which you are trying to use dispatch on

![image](https://github.com/69Type/istrusted-bypass/assets/96850544/278ae6ac-72d2-40ec-9ec1-000cf60ec635)
I added a print for these args:
![image](https://github.com/69Type/istrusted-bypass/assets/96850544/01694cdb-6f06-40f3-8abb-63ba4c342b8f)

and for some reason its undefined when there is a listener on it

**Comment by namecallfilter** [comment]
![image](https://github.com/69Type/istrusted-bypass/assets/96850544/68b68bc5-8094-47e8-a6b6-1cb4e5c6bd09)
onclick is the only listener

**Comment by namecallfilter** [comment]
OMG I GOT IT WORKING, they have an option for clicking the 1,2,3,4 for the answer and it worked

**Comment by namecallfilter** [comment]
thanks for the help!
